INSERT INTO episodes (key, title, season, episode_number, director)
VALUES 
    ('S1E01', 'Pilot', 1, 1, 'Anthony Russo & Joe Russo'),
    ('S1E02', 'Top Banana', 1, 2, 'Anthony Russo'),
    ('S1E03', 'Bringing Up Buster', 1, 3, 'Joe Russon'),
    ('S1E04', 'Key Decisions', 1, 4, 'Anthony Russo'),
    ('S1E05', 'Visiting Ours', 1, 5, 'Greg Mottola'),
    ('S1E06', 'Charity Drive', 1, 6, 'Greg Mottola'),
    ('S1E07', 'My Mother, the Car', 1, 7, 'Jay Chandrasekhar'),
    ('S1E08', 'In God We Trust', 1, 8, 'Joe Russo'),
    ('S1E09', 'Storming the Castle', 1, 9, 'Greg Mottola'),
    ('S1E10', 'Pier Pressure', 1, 10, 'Joe Russo'),
    ('S1E11', 'Public Relations', 1, 11, 'Lee Shallat Chemel'),
    ('S1E12', 'Marta Complex', 1, 12, 'Joe Russo'),
    ('S1E13', 'Beef Consomme', 1, 13, 'Jay Chandrasekhar'),
    ('S1E14', 'Shock and Aww', 1, 14, 'Joe Russo'),
    ('S1E15', 'Staff Infection', 1, 15, 'John Fortenberry'),
    ('S1E16', 'Missing Kitty', 1, 16, 'Joe Russo'),
    ('S1E17', 'Altar Egos', 1, 17, 'Jay Chandrasekhar'),
    ('S1E18', 'Justice Is Blind', 1, 18, 'Jay Chandrasekhar'),
    ('S1E19', 'Best Man for the Gob', 1, 19, 'Lee Shallat Chemel'),
    ('S1E20', 'Whistler''s Mother', 1, 20, 'Paul Feig'),
    ('S1E21', 'Not Without My Daughter', 1, 21, 'Lee Shallat Chemel'),
    ('S1E22', 'Let ''Em Eat Cake', 1, 22, 'Paul Feig'),
    ('S2E01', 'The One Where Michael Leaves', 2, 1, 'Lee Shallat Chemel'),
    ('S2E02', 'The One Where They Build a House', 2, 2, 'Patty Jenkins'),
    ('S2E03', '¡Amigos!', 2, 3, 'Lee Shallat Chemel'),
    ('S2E04', 'Good Grief!', 2, 4, 'Jeff Melman'),
    ('S2E05', 'Sad Sack', 2, 5, 'Peter Lauer'),
    ('S2E06', 'Afternoon Delight', 2, 6, 'Jason Bateman'),
    ('S2E07', 'Switch Hitter', 2, 7, 'Paul Feig'),
    ('S2E08', 'Queen for a Day', 2, 8, 'Andrew Fleming'),
    ('S2E09', 'Burning Love', 2, 9, 'Paul Feig'),
    ('S2E10', 'Ready, Aim, Marry Me', 2, 10, 'Paul Feig'),
    ('S2E11', 'Out on a Limb', 2, 11, 'Danny Leiner'),
    ('S2E12', 'Hand to God', 2, 12, 'Joe Russo'),
    ('S2E13', 'Motherboy XXX', 2, 13, 'Joe Russo'),
    ('S2E14', 'The Immaculate Election', 2, 14, 'Anthony Russo'),
    ('S2E15', 'Sword of Destiny', 2, 15, 'Peter Lauer'),
    ('S2E16', 'Meat the Veals', 2, 16, 'Joe Russo'),
    ('S2E17', 'Spring Breakout', 2, 17, 'Anthony Russo'),
    ('S2E18', 'Righteous Brothers', 2, 18, 'Chuck Martin'),
    ('S3E01', 'The Cabin Show', 3, 1, 'Paul Feig'),
    ('S3E02', 'For British Eyes Only', 3, 2, 'John Fortenberry'),
    ('S3E03', 'Forget-Me-Now', 3, 3, 'John Amodeo'),
    ('S3E04', 'Notapusy', 3, 4, 'Lev L. Spiro'),
    ('S3E05', 'Mr. F', 3, 5, 'Arlene Sanford'),
    ('S3E06', 'The Ocean Walker', 3, 6, 'Paul Feig'),
    ('S3E07', 'Prison Break-In', 3, 7, 'Robert Berlinger'),
    ('S3E08', 'Making a Stand', 3, 8, 'Peter Lauer'),
    ('S3E09', 'S.O.B.s', 3, 9, 'Robert Berlinger'),
    ('S3E10', 'Fakin'' It', 3, 10, 'Lev L. Spiro'),
    ('S3E11', 'Family Ties', 3, 11, 'Robert Berlinger'),
    ('S3E12', 'Exit Strategy', 3, 12, 'Rebecca E. Asher'),
    ('S3E13', 'Development Arrested', 3, 13, 'John Fortenberry');