name: Deploy To AWS
on:
 push:
   branches:
     main

permissions:
  id-token: write

env:
  AWS_REGION: "us-east-1"
  ECR_API_REPOSITORY: ${{ secrets.ECR_API_REPOSITORY }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          role-to-assume: ${{ secrets.AWS_ACTIONS_ROLE_ARN }}
          role-session-name: github-actions-session
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a

      - name: Build, tag, and push API image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_API_REPOSITORY:$IMAGE_TAG ./api
          docker push $ECR_REGISTRY/$ECR_API_REPOSITORY:$IMAGE_TAG
          
  
